repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--fix", "--extend-select", "I", "--config", "./pyproject.toml"]
      # Run the formatter.
      - id: ruff-format
        args:
          [
            "--config",
            "line-length = 100",
            "--config",
            'format.quote-style = "single"',
          ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
